version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "99:f0:fa:49:b5:cb:eb:d2:b8:69:d0:d3:28:74:25:9e"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
