version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: echo "Hello"
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
