version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation create-stack \
            --stack-name forCircleCI \
            --parameters template.yml
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
