version: 2.1
jobs:
  fake_smoke_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: if curl -s --head "https://google.com"; then
              echo "URL exists"
               else
              echo "URL does not exist"
               fi
workflows:
  my_workflow:
    jobs:
      - fake_smoke_test
