version: 2.1
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: echo ${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name "toproduction"
            --parameter-overrides PipelineID="toproduction"
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
          --template-file cloudfront.yml \
          --stack-name production-distro \
          --parameter-overrides PipelineID="toproduction"
  get_last_deployment_id:
    working_directory: ~/tmp
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation \
          list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
          --no-paginate --output text >> inventory.txt
      - persist_to_workspace:
          root: .
          paths:
            - inventory.txt
  clean_up_old_front_end:
    working_directory: ~/tmp
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp
      - run: cat inventory.txt
      - run: |
          aws s3 rm "s3://${OldPipelineID}" --recursive
          aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"
workflows:
  version: 1
  production_pipe:
    jobs:
      - create_and_deploy_front_end
      - promote_to_production:
          requires:
            - create_and_deploy_front_end
