version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f2:62:fd:e1:f7:86:4b:77:5d:7e:20:b6:a7:f7:02:fe"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
