version: 2.1
jobs:
  fake_smoke_test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: smoke test
          command: |
              URL="https://www.google.com/"
              if curl -s --head ${URL}
              then
               return 0
              else
               return 1
              fi
workflows:
  my_workflow:
    jobs:
      - fake_smoke_test
